[project]
name = "auto_doc_generator"
version = "0.1.0"
description = "Generative AI application to generate markdown content automatically"
requires-python = ">=3.12"

dependencies = [
    "langchain",
    "langgraph",
    "pydantic",
    "pydantic-settings",
    "langchain-google-genai"
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "mypy",
]