from pydantic import BaseModel, Field

from models.metadata import Metadata


class RetrievalResult(BaseModel):
    """
    Retrieved chunk with similarity score.
    """

    metadata: Metadata

    content: str

    score: float


class GeneratedSection(BaseModel):
    """
    Markdown generated by the writer.
    """

    title: str

    markdown: str

    sources: list[str] = Field(default_factory=list)


class ValidationReport(BaseModel):
    """
    Validation output for a generated section.
    """

    section: str

    passed: bool

    issues: list[str] = Field(default_factory=list)
