from pydantic import BaseModel, Field

from models.metadata import Metadata


class RawDocument(BaseModel):
    """
    Raw HTML downloaded from a documentation page.
    """

    metadata: Metadata

    html: str


class CleanDocument(BaseModel):
    """
    Cleaned markdown/text extracted from HTML.
    """

    metadata: Metadata

    content: str


class Chunk(BaseModel):
    """
    Small searchable chunk used for embeddings.
    """

    metadata: Metadata

    content: str


class RetrievalResult(BaseModel):
    """
    Retrieved chunk with similarity score.
    """

    metadata: Metadata

    content: str

    score: float


class GeneratedSection(BaseModel):
    """
    Markdown generated by the writer.
    """

    title: str

    markdown: str

    sources: list[str] = Field(default_factory=list)


class ValidationReport(BaseModel):
    """
    Validation output for a generated section.
    """

    section: str

    passed: bool

    issues: list[str] = Field(default_factory=list)